language: node_js
node_js:
- '8'
install: npm install
script: true
addons:
  ssh_known_hosts: 140.143.170.28
before_install:
- openssl aes-256-cbc -K $encrypted_1b7beeacf6f9_key -iv $encrypted_1b7beeacf6f9_iv
  -in server.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
after_success:
- ssh $SERVER_USER@$SERVER_IP "sh ~/www/blog.sh"
branches:
  only:
  - master
env:
  global:
    secure: FyPlSa4+YrmgATsF+neiyMS2gwjVtGRYoJ84rnybY+WATFos66o7h0+CYufdlOjcd7cQH/m8IwRAG0scqdsJdJSGPKG1CTN1RFWvcbuA4oxQO1oIpLrAu51b4MhXk9HUxC+WC+IaUIKnApVTFHRrbzH83bzkJS+aBEU3boxCXa36DATyQFwBiXT3itw1YgSb1cFFqo9k/wZ61FvzxknJQqj0HEErpyPLLiNBFByUyWVRO1u8VV2JyWM0/KF+L48DS55A+IKt9lqM/frB+CbN1O6eBcHZx7zmodq5qu0+vR3+0XTam4wSWo/ynGROYrfRLCYOCTc+FfGLX7k7M9blzeXtvdtCyoyKGNHsoXGUglmsa95sq0/6u2A4tttLuuFb0b2zLOaD6glSl89WPYT74I+ASWmndtSY+8YAPEateUR7eIY5fvq/ULJE7pMV/3pIEAfVhHOLSTdllFji+1CaZ3sAymY/msVXKkt25qK95HBvKIiI+qlTlFMQAiQ2Mtj/LbCW/aVur/1ZtbPXQmNyQxWwwTWHH1UbmqNoQJwkEwdaeaMKJcSf14/Ac4IHCFcX85kubbdIMzuqNmlkC187zOXIDqAsblFYpa+Wmojl03+ccGdaMQi3U37uhIGWKJPgTJx1M6ItE6c4FOV2be/MzxUQlVZVX95v4S5cEKgjw9E=
