language: node_js
node_js:
- '8'
install: npm install
script: true
addons:
  ssh_known_hosts: 140.143.170.28
before_install:
- openssl aes-256-cbc -K $encrypted_31943c0bbef1_key -iv $encrypted_31943c0bbef1_iv
  -in server.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
after_success:
- ssh $SERVER_USER@$SERVER_IP "sh ~/www/blog.sh"
branches:
  only:
  - master
env:
  global:
    secure: bPXvqVQUejoRqpfgp/Fe6eVNNGLiguCyJ8v/nZz7DzmVS8R96C1VrcjUUspUs/+aLDLjYHEzbXdRUeVnC7QWqJ6s2RcPcCt4ebKeoHl2lMW4tV0Kw7L9Ie1N7SKgbu0gtI7m1Oki0EvA7NGzaGEYXcmhoCykzJRKPCmSBclqRO+TqDitBHw8zJdBui2UpG7g5FCKvWW6FEXW0xbnZZ9TTymYgCvKxvVf/+utn9yUvyC1kwcdTHFI0RohaC5jInKkrdVaDp+MNcf9gOfTxfXflJNG8xBPE4FaQ5uBYnpAXJYlC2wOFxImKv94HDoXpI5EhSUtaMPJBOT8tCeQAmU/3PDisHHP8ECvdQlWUMUnm3BvDWYCVe743YfZd3PCgUM01ILUosof5Qi1oqlaJkYi71FYsRfqFOv3WTNYQFp5bgttyuKrjc7gzlI49FJeiQIOCihNyIrKs7VNK28h2olTGYSGeU6oNed3504JWwIsKo2hyvRwanimahzq6UJPmHaMLOpBn7fr00FlnTpQBAewthPddPjHVDccpVq38MPt6X+mmgdjcajl4dr/AzqnngFx6wMTMn0fz/Nz3CPfY479fx4BPlX1VSN4JaVfYwSTQBH1caRtEONOZG+275EVffw37+d3M0dLRUyOquxvW8R/ePxC1vBrnRWL3MkjoMuEy7E=
